name: tests

on: [push, pull_request]

jobs:
  integration:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]

    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Alcor CLI
      run: |
          python -m pip install --upgrade pip
          pip install -e .

    - name: Install Alcor
      run: |
        alcor init $(pwd)/alcor
        alcor activate --auto
        exec bash
        module spider

    - name: Test Install Module
      run: |
        bash tests/integration/test_install_module.sh

    - name: Test Install Apt
      run: |
        bash test/integration/test_install_apt.sh

